# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: payment
#   labels:
#     project: roboshop
#     component: payment
#     tier: web-teir

# data:
#   CART_ENDPOINT: "cart:8080" 
#   DB_HOST: "mysql"
---
apiVersion: v1
kind: Deployment
metadata: 
  name: payment
  namespace: roboshop
  #replica set labels which can used under selectors to club the images
  labels:
    project: roboshop
    component: payment
    tier: web-teir
spec:
  replicas: 1
  # these are the labels replica set labels to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: payment
      tier: web-teir
  #this is pod defnition template
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: web-teir
    spec:
      containers:
        - name: payment
          image: pardhu72/payment:v1
          # envFrom:
          #   - configMapRef:
          #       name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: web-teir
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: payment
    tier: web-tier
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
