apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    project: roboshop
    component: rabbitmq
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "decoded value"
  RABBITMQ_DEFAULT_PASSWORD: "Default password"
  
---
apiVersion: v1
kind: Deployment
metadata: 
  name: rabbitmq
  namespace: roboshop
  #replica set labels which can used under selectors to club the images
  labels:
    project: roboshop
    component: rabbitmq
    tier: database
spec:
  replicas: 1
  # these are the labels replica set labels to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: database
  #this is pod defnition template
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: database
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3S

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: database
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: database
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port
