apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  labels:
    project: roboshop
    component: catalogue
    tier: app-tier

data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  #replica set labels which can used under selectors to club the images
  labels:
    project: roboshop
    component: catalogue
    tier: app-tier
spec:
  replicas: 1
  # these are the labels replica set labels to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: app-tier
  #this is pod defnition template
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: app-tier
    spec:
      containers:
        - name: catalogue
          image: pardhu72/catalogue:v1
          envFrom:
            - configMapRef:
                name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: app-tier
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: app-tier
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
